setup:
  Node1:
    ips:
      - eth: eth1
        ipv4: 10.0.0.1
        route: 10.0.1.0/24
        gw: 10.0.0.2
    name: n1
  Router1:
    ips:
      - eth: eth1
        ipv4: 10.0.0.2
      - eth: eth2
        ipv4: 10.0.1.1
    name: r1
  Node2:
    ips:
      - eth: eth1
        ipv4: 10.0.1.2
        route: 10.0.0.0/24
        gw: 10.0.1.1
    name: n2
