setup:
  R0:
    ips:
      - eth: eth1
        ipv4:  10.0.2.100
        id: 1
      - eth: eth2
        ipv4:  10.0.0.100
        id: 2
      - eth: eth3
        ipv4:  10.0.1.100
        id: 3
    name: r0
  R1:
    ips:
      - eth: eth1
        ipv4:  10.0.2.101
        id: 3
      - eth: eth2
        ipv4:  10.0.4.101
        id: 5
      - eth: eth3
        ipv4:  10.0.3.100
        id: 4
    name: r1
  R2:
    ips:
      - eth: eth1
        ipv4:  10.0.4.100
        id: 5
      - eth: eth2
        ipv4:  10.0.5.100
        id: 6
      - eth: eth3
        ipv4:  10.0.6.100
        id: 7
    name: r2

  B0:
    ips:
      - eth: eth1
        ipv4:  10.0.1.1
        id: 1
    name: b0
  B1:
    ips:
      - eth: eth1
        ipv4:  10.0.3.1
        id: 3
    name: b1
  B2:
    ips:
      - eth: eth1
        ipv4:  10.0.5.1
        id: 5
    name: b2

  KS0:
    ips:
      - eth: eth1
        ipv4:  10.0.1.2
        id: 1
    name: ks0
  KS1:
    ips:
      - eth: eth1
        ipv4:  10.0.3.2
        id: 1
    name: ks1
  KS2:
    ips:
      - eth: eth1
        ipv4:  10.0.5.2
        id: 1
    name: ks2

  C0:
    ips:
      - eth: eth1
        ipv4:  10.0.0.1
        id: 1
    name: c0
  C1:
    ips:
      - eth: eth1
        ipv4:  10.0.0.2
        id: 1
    name: c1
  charlie:
    ips:
      - eth: eth1
        ipv4:  10.0.0.3
        id: 1
    name: charlie 

  P0:
    ips:
      - eth: eth1
        ipv4:  10.0.6.1
        id: 7
    name: p0
  P1:
    ips:
      - eth: eth1
        ipv4:  10.0.6.2
        id: 7
    name: p1
