---
- hosts: all
  tasks:
    - name: install code prerequisites 
      become: yes
      apt:
        name: 
          - tmux
          - apt
          - openssl
          - build-essential
          - autoconf
          - docker.io
        state: present
        update_cache: yes

    - name: kill all docker containers and images
      command: sh /palisades/scripts/stop_docker.sh
      become: yes
      ignore_errors: yes
      when: inventory_hostname != "Router1"

    - name: load docker image of examples with palisade base
      shell: sudo docker load -i /palisades/dockerimages/examples-min.tar
      become: yes
      when: inventory_hostname != "Router1"

    - name: run node1 script, make sure the script is bash & backgrounded
      command: sh /palisades/scripts/node1/run_script.sh {{ ssl_authentication }} {{ input_file }}
      become: yes
      when: inventory_hostname == "Node1"

    - name: run node2 script, make sure the script is bash & backgrounded
      command: sh /palisades/scripts/node2/run_script.sh {{ ssl_authentication }} {{ input_file }}
      become: yes
      when: inventory_hostname == "Node2"

    - name: get the output from the docker container
      command: sh /palisades/scripts/node1/print_output.sh
      become: yes
      when: inventory_hostname == "Node1"

    - name: get the output from the docker container
      command: sh /palisades/scripts/node2/print_output.sh
      become: yes
      when: inventory_hostname == "Node2"
