package(default_visibility = ["//visibility:public"])

load("//bazel:cc_grpc_library.bzl", "cc_grpc_library")

cc_grpc_library(
    name = "thresh_net_cpp_grpc",
    srcs = ["thresh_net.proto"],
    grpc_only = True,
)

