---
- hosts: all
  serial: 1
  tasks:
    - name: kill all docker containers and images
      command: sh /palisades/scripts/stop_docker.sh
      become: yes
      ignore_errors: yes
      when: 
        - "'R' not in inventory_hostname"
        - "('S' not in inventory_hostname) or ('KS' in inventory_hostname)"

    - name: load docker image of examples with palisade base
      shell: sudo docker load -i /palisades/dockerimages/examples-min.tar
      become: yes
      when: 
        - "'R' not in inventory_hostname"
        - "('S' not in inventory_hostname) or ('KS' in inventory_hostname)"

    - name: run key server script, make sure the script is bash & backgrounded
      command: sh /palisades/scripts/key_server/run_script.sh {{ ssl_authentication }} {{ inventory_hostname }} {{ network_map }} {{ access_map }} {{ hostnames }}
      become: yes
      when: "'KS' in inventory_hostname"

    - name: run broker script, make sure the script is bash & backgrounded
      command: sh /palisades/scripts/broker/run_script.sh {{ ssl_authentication }} {{ inventory_hostname }} {{ network_map }} {{ hostnames }}
      become: yes
      when: "'B' in inventory_hostname"

    - name: run producer script, make sure the script is bash & backgrounded
      command: sh /palisades/scripts/producer/run_script.sh {{ ssl_authentication }} {{ inventory_hostname }} {{ network_map }} {{ hostnames }}
      become: yes
      when: inventory_hostname == producer_name

    - name: run consumer script, make sure the script is bash & backgrounded
      command: sh /palisades/scripts/consumer/run_script.sh {{ ssl_authentication }} {{ inventory_hostname }} {{ producer_name }} {{ network_map }} {{ hostnames }}
      become: yes
      when: inventory_hostname == consumer_name

    - name: get the output from the docker container
      command: sh /palisades/scripts/producer/print_output.sh 
      become: yes
      when: inventory_hostname == producer_name

    - name: get the output from the docker container
      command: sh /palisades/scripts/consumer/print_output.sh {{ inventory_hostname }} {{ producer_name }}
      become: yes
      when: inventory_hostname == consumer_name
