setup:
  R0:
    ips:
      - eth: eth1
        ipv4:  10.0.2.100
        id: 1
      - eth: eth2
        ipv4:  10.0.0.100
        id: 2
      - eth: eth3
        ipv4:  10.0.1.100
        id: 3
    name: r0
  B0:
    ips:
      - eth: eth1
        ipv4:  10.0.0.1
        id: 2
    name: b0
  KS0:
    ips:
      - eth: eth1
        ipv4:  10.0.0.2
        id: 2
    name: ks0
  B1:
    ips:
      - eth: eth1
        ipv4:  10.0.0.3
        id: 2
    name: b1
  C0:
    ips:
      - eth: eth1
        ipv4:  10.0.2.1
        id: 1
    name: c0
  C1:
    ips:
      - eth: eth1
        ipv4:  10.0.2.2
        id: 1
    name: c1
  charlie:
    ips:
      - eth: eth1
        ipv4: 10.0.2.3
        id: 1
    name: charlie 

  P0:
    ips:
      - eth: eth1
        ipv4:  10.0.1.1
        id: 3
    name: p0
  P1:
    ips:
      - eth: eth1
        ipv4:  10.0.1.2
        id: 3
    name: p1
