---
- hosts: all
  tasks:
    - name: install code prerequisites 
      become: yes
      apt:
        name: 
          - tmux
          - apt
          - openssl
          - build-essential
          - autoconf
          - docker.io
        state: present
        update_cache: yes
      when: "('S' not in inventory_hostname) or ('KS' in inventory_hostname)"
