---
- hosts: routers
  become: yes
  tasks:
    - name: include our variables for the build
      include_vars: vars/hosts.yml

    - name: Recursively remove directory
      file:
        path: /etc/apt/sources.list.d/frr.list
        state: absent

    - name: install lsb-release for frr script
      shell: apt-get --allow-releaseinfo-change update

    - name: install lsb-release for frr script
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - lsb-release
        - gnupg2

    - name: copy frr deb script
      copy:
        src: files/add-frr.sh
        dest: /etc/apt/add-frr.sh
        owner: root
        group: root
        mode: 0755
 
    # bug in current frr 7.5.1 with ospfv6, missing conf t, int eth1, ipv6 ospf6 area option (which enables ospf on the interface- big oops)   
    - name: add frr deb
      command: /etc/apt/add-frr.sh

    - name: install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - ntp
        - ethtool
        - frr
        - tcpdump
        - lldpd

    - name: set hostname
      hostname:
        name: "{{ setup[inventory_hostname].name }}"

    - name: stop frr
      systemd:
        name: frr
        state: stopped

    - name: remove address from ifaces
      command: "ip addr flush dev {{ item.eth }}"
      ignore_errors: yes
      loop: "{{ setup[inventory_hostname].ips }}"

    #- name: add address v6
    #  command: "ip addr add {{ item.ipv6 }}/120 dev {{ item.eth }}"
    #  loop: "{{ setup[inventory_hostname].ips }}"

    - name: add address v4
      command: "ip addr add {{ item.ipv4 }}/24 dev {{ item.eth }}"
      loop: "{{ setup[inventory_hostname].ips }}"

    - name: set interface up
      command: "ip link set dev {{ item.eth }} up"
      loop: "{{ setup[inventory_hostname].ips }}"

    - name: copy over sysctl file
      copy:
        src: files/frr_defaults.conf
        dest: /etc/sysctl.d/99frr_defaults.conf
        owner: root
        group: root

    - name: make sysctl settings persist
      command: sysctl -p /etc/sysctl.d/99frr_defaults.conf

    - name: copy over daemons file
      copy:
        src: files/daemons
        dest: /etc/frr/daemons
        owner: root
        group: root

    - name: copy over template
      template:
        src: templates/frr.conf
        dest: /etc/frr/frr.conf
        owner: root
        group: root

    - name: reload frr
      systemd:
        name: frr
        daemon_reload: yes
        state: reloaded

    - name: restart frr
      systemd:
        name: frr
        state: restarted

    - name: setup custom dns
      template:
        src: hosts.template
        dest: /etc/hosts
      become: yes

- hosts: switches
  become: true
  tasks:
    - name: configure switch ports for S0
      nclu:
        commands:
          - add bridge bridge ports swp1-4
          - add int swp1 bridge access 1
          - add int swp2 bridge access 1
          - add int swp3 bridge access 1
          - add int swp4 bridge access 1
        atomic: true
      when: inventory_hostname == "S0"
      tags:
        - patch

    - name: configure switch ports for S1+
      nclu:
        commands:
          - add bridge bridge ports swp1-3
          - add int swp1 bridge access 1
          - add int swp2 bridge access 1
          - add int swp3 bridge access 1
        atomic: true
      when: inventory_hostname != "S0"
      tags:
        - patch


- hosts: nodes
  become: yes
  tasks:
    - name: include our variables for the build 2
      include_vars: vars/hosts.yml

    - name: setup custom dns
      template:
        src: hosts.template
        dest: /etc/hosts

    - name: remove address from ifaces
      command: "ip addr flush dev {{ item.eth }}"
      ignore_errors: yes
      loop: "{{ setup[inventory_hostname].ips }}"

    - name: add address v4
      command: "ip addr add {{ item.ipv4 }}/24 dev {{ item.eth }}"
      loop: "{{ setup[inventory_hostname].ips }}"

    - name: set interface up
      command: "ip link set dev {{ item.eth }} up"
      loop: "{{ setup[inventory_hostname].ips }}"

    - name: set default routes 2
      command: ip route add 10.0.0.0/16 dev eth1 via {{ ".".join(item.ipv4.split(".")[:-1]) }}.100
      loop: "{{ setup[inventory_hostname].ips }}"

